export const valuesNames = {
  DATE: 'documentDate',
  AUTHOR: 'author_name',

  FACILITY: 'facility',
  FACILITY_PROVIDER_ID: 'providerContact_id',

  // Disharge
	TYPE: 'documentType',
	DATE_CREATED: 'dateCreated',
  NAME: 'documentName',

  PI_MRNTYPE : 'patientIdentifier_mrnType',
  PI_OTHTYPE : 'patientIdentifier_othType',
  PI_GMSTYPE : 'patientIdentifier_gmsType',
  PI_NAME : 'responsibleProfessional_name',
  PI_ID_TYPE: 'responsibleProfessional_idType',
  PI_SOURCE: 'source',
  PI_DISHARGING: 'dischargingOrganisation',
  PI_DISHARGING_DATE: 'dateTimeOfDischarge',
  PI_CLINICAL: 'clinicalSynopsis',
  PI_ADMISSION_DATE: 'dateOfAdmission',

  DIAGNOSIS: 'diagnosisList',
  DG_PROBLEM: 'problem',
  DG_DESCR: 'description',
  DG_TERMINOLOGY: 'terminology',
  DG_TERMINOLOGY_CODE: 'terminologyCode',

  // Referral
  COMPOSER_NAME: 'composerName',
  REFERRAL_DATE: 'referralDateTime',
  REFERRAL_TYPE: 'referralType',
  REFERRAL_STATUS: 'referralStatus_value',
  REFERRAL_REF: 'referralReferenceNumber',
  REFERRAL_FROM: 'referredFrom',
  REFERRAL_TO: 'referredTo',
  REFERRAL_COMMENTS: 'referralComments',
  REFERRAL_REASONS: 'reasonForReferral',
  REFERRAL_REASON: 'reason',

  PROVIDER_NAME: 'providerContact_organisationName',
  PROVIDER_ID: 'providerContact_id',
  PROVIDER_WORK_PHONE: 'providerContact_workNumber',
  PROVIDER_EMERGENCY_PHONE: 'providerContact_emergencyNumber',
  PROVIDER_EMAIL_PHONE: 'providerContact_email',

  STATUS: 'referralStatus_value',
  STATUS_ORIGINAL_CODE: 'referralStatus_originalCode',
  STATUS_CODE: 'referralStatus_code',

  SYNOPSIS_NARRATIVE: 'clinicalNarrative',
  SYNOPSIS_ILLNESS: 'presentIllness',
  SYNOPSIS_COMMENTS: 'clinicalSynopsisComments',
  SYNOPSIS_HOSPITAL: 'previousHospitalAttendance',

  PAST_I_HYPERTENSION: 'pastIllensses',
  PAST_I_HYPERTENSION_VALUE: 'value',
  PAST_I_HYPERTENSION_DATE: 'date',

  SP_CONCLUSION: 'conclusion',
  SP_CONCLUSION_VALUE: 'value',
  SP_CONCLUSION_DATE: 'date',

  MEDICATIONS: 'medications',
  M_NAME: 'name',
  M_START_DATE: 'startDate',
  M_TIME: 'startTime',
  M_DOSE_A: 'doseAmount',
  M_DOSE_D: 'doseDirections',
  M_DOSE_T: 'doseTiming',
  M_ROUTE: 'route',
  M_TERMINOLOGY: 'termonology',
  M_CODE: 'code',
  M_AUTHOR: 'author_name',
  M_DATE: 'startDate',
  M_SOURCE: 'source',
  M_USE: 'medication_anticoagulation_use',

  ALLERGIES: 'allergies',
  A_NAME: 'testName',
  A_STATUS: 'status',
  A_TAKEN: 'sampleTaken',
  A_TERMINOLOGY: 'conclusion',
  A_TERMINOLOGY_CODE: 'conclusion',
  A_AUTHOR: 'author',
  A_DATE_CREATED: 'dateCreated',
  A_SOURCE: 'source',

  USE_TOBACCO: 'tobaccoUse',
  USE_ALCOHOL: 'alcoholUse',
  PHYSICAL_I: 'physicalImparement',

  V_SBP: 'systolicBP',
  V_SBPU: 'systolicBP_units',
  V_DBP: 'diastolicBP',
  V_DBPU: 'diastolicBP_units',
  V_P: 'pulse',
  V_PU: 'pulse_units',
  V_H: 'height',
  V_HU: 'height_units',
  V_W: 'weight',
  V_WU: 'weight_units',
  V_BM: 'bodyMass',
  V_BMU: 'bodyMass_units',

  OTHER_EXAM: 'otherExaminationFindings',
  DOC_ORIGINAL_SOURCE: 'documentOriginalSource',

  SOURCE: 'source',
  SOURCE_ID: 'sourceId',
};

export const valuesLabels = {
  DATE: 'Document Date',
  AUTHOR: 'Author',

  TITLE_FACILITY: 'Facility',
  FACILITY: 'Name',
  FACILITY_PROVIDER_ID: 'Provide ID',

  // Disharge
	TYPE: 'Name',
  DATE_CREATED: 'Date',
  NAME: 'Document Name',

  TITLE_PATIENT_INDENTIFIER: 'Patient Identifier',
  PI_MRNTYPE : 'MRM Type',
  PI_OTHTYPE : 'OTH Type',
  PI_GMSTYPE : 'GMS Type',
  PI_NAME : 'Responsible Professional',
  PI_ID_TYPE: 'Responsible Professional Type',
  PI_SOURCE: 'From',
  PI_DISHARGING: 'Discharging Organisation',
  PI_DISHARGING_DATE: 'Discharging Date',
  PI_CLINICAL: 'Clinical Synopsis',
  PI_ADMISSION_DATE: 'Date of Admission',

  TITLE_DIAGNOSIS: 'Diagnosis List',
  DG_PROBLEM: 'Problem',
  DG_DESCR: 'Description',
  DG_TERMINOLOGY: 'Terminology',
  DG_TERMINOLOGY_CODE: 'Terminology Code',


  // Referral
  COMPOSER_NAME: 'Document Name',

  TITLE_REFERRAL: 'Referral',
  REFERRAL_DATE: 'Date',
  REFERRAL_TYPE: 'Type',
  REFERRAL_STATUS: 'Priority',
  REFERRAL_REF: 'Ref',
  REFERRAL_FROM: 'From',
  REFERRAL_TO: 'To',
  REFERRAL_COMMENTS: 'Comments',
  REFERRAL_REASONS: 'Comments',

  TITLE_PROVIDER: 'Organisation/Provide',
  PROVIDER_NAME: 'Name',
  PROVIDER_ID: 'ID',
  PROVIDER_WORK_PHONE: 'Work Phone',
  PROVIDER_EMERGENCY_PHONE: 'Emergency Phone',
  PROVIDER_EMAIL_PHONE: 'Email',

  TITLE_STATUS: 'Referral Status',
  STATUS: 'Status',
  STATUS_ORIGINAL_CODE: 'Original Code',
  STATUS_CODE: 'Code',

  TITLE_SYNOPSIS: 'Clinical Synopsis',
  SYNOPSIS_NARRATIVE: 'Narrative',
  SYNOPSIS_ILLNESS: 'Present Illness',
  SYNOPSIS_COMMENTS: 'Comments',
  SYNOPSIS_HOSPITAL: 'Previous Hospital',

  TITLE_PAST_ILLNESS: 'Past Illness',
  PAST_I_HYPERTENSION: 'Hypertension',

  TITLE_SURGICAL_PROCEDURES: 'Surgical Procedures',
  SP_CONCLUSION: 'Hypertension',

  TITLE_MEDICATIONS: 'Medications',
  M_NAME: 'Name',
  M_START_DATE: 'Start Date',
  M_TIME: 'Start Time',
  M_DOSE_A: 'Dose Amount',
  M_DOSE_D: 'Dose Directions',
  M_DOSE_T: 'Dose Timing',
  M_ROUTE: 'Route',
  M_TERMINOLOGY: 'Terminology',
  M_CODE: 'Code',
  M_AUTHOR: 'Author',
  M_DATE: 'Date',
  M_SOURCE: 'Source',
  M_USE: 'Medication Anticoagulation Use',

  TITLE_ALLERGIES: 'Allergies',
  A_NAME: 'Cause',
  A_STATUS: 'Cause',
  A_TAKEN: 'Cause Code',
  A_TERMINOLOGY: 'Reaction',
  A_TERMINOLOGY_CODE: 'Terminology',
  A_AUTHOR: 'Terminology Code',
  A_DATE_CREATED: 'Author',
  A_SOURCE: 'Date',

  USE_TOBACCO: 'Tobacco Use',
  USE_ALCOHOL: 'Alcohol Use',
  PHYSICAL_I: 'Physical Impairment',

  TITLE_VITALS: 'Measurements',
  V_SBP: 'Systolic BP',
  V_SBPU: 'Systolic BP Units',
  V_DBP: 'Diastolic BP',
  V_DBPU: 'Diastolic BP Units',
  V_P: 'Pulse',
  V_PU: 'Pulse Units',
  V_H: 'Height',
  V_HU: 'Height Units',
  V_W: 'Weight',
  V_WU: 'Weight Units',
  V_BM: 'Body Mass',
  V_BMU: 'Body Mass Units',

  OTHER_EXAM: 'Other Examination Findings',
  DOC_ORIGINAL_SOURCE: 'Original Source',

  SOURCE: 'Source',
	SOURCE_ID: 'Source ID',
};
