export const themeConfigs = {
  isLeedsPHRTheme: true,
  topHeader: {
    showNotifications: false,
    showQuestions: true,
    showSearch: false,
    showUserPanel: true,
  },
  isLeedsPHRHeaderList: true,
  headerHasSearch: false,
  footerHasShowSupportedByText: false,
  footerCopyright: 'Copyright 2017 Ripple Foundation CIC Ltd. All rights reserved',
  isShowPluginsBigBanner: true,
  patientsSummaryPageName: 'Home',
  patientsSummaryHasPreviewSettings: true,
  sidebarConfigIsVisible: {
    default: false,
    'patients-summary': true,
    'diagnoses': true,
    'medications': true,
    'allergies': true,
    'contacts': true,
    'vaccinations': true,
    'topThreeThings': true,
  },
  dashboardBeing: {},
  isShowUserPhoto: false,
  isShowUserProfileSettings: false,
  isShowUserProfileSpecification: false,
  patientsSummaryTitles: {
    'diagnoses': 'Problems / Issues',
    'medications': 'Medications',
    'allergies': 'Allergies',
    'contacts': 'Contacts',
    'vaccinations': 'Vaccinations',
    'topThreeThings': 'Top Three Things',
  },
  detailsToHide: {
    'allergies': ['causeCode', 'causeTerminology'],
    'diagnoses': ['terminology', 'code'],
    'medications': ['doseTiming', 'doseAmount'],
  },
  buttonsToHide: {
    'diagnoses': ['create', 'edit'],
    'medications': ['create', 'edit', 'cancel', 'suspend', 'order'],
    'allergies': ['create', 'edit'],
    'vaccinations': ['create', 'edit'],
  },
  panelsToHide: {
    'medications': ['history', 'prescription', 'warnings'],
  }
};
